language: node_js
node_js:
 - "8"
install:
 - npm install
addons:
  sonarcloud:
    organization: "boxrec"
    token:
      secure: "k8G1N4PUFS/RoMkPfdpEGLHbp25avfGIrMK3vLR2lJEIE9n/vAqHgC05RBTxLK+peK1raDVBBNqrXcDZx/Ei8olJU7y6OCqeZipigT/sZWI3ZEjPPrWbSa30kTlqedBTpMrclY3bL+AXn24Xg/oiiR8CBz8NBNwRi4SPlaLLvMf+olHxhluJs97Io8SGMn1zhzwvhxlYTIWTRT6c35fj2ChN2qV0dAicqrgb5wNFdunVPumhQZzMcxq6hG4Qqyw3xII+hB02AXRjBcwse8lg7fbJ/4is6vxcKgnBbDIoyKSEqvn9YKIkCqBEnEbj/HeaJWT3ErcBTE4mnBEhBBuSTfd8GlshTRovONd1kGhys9pH+WDObceefiuhr9Pze38gJ34eBBVFGVo/7mzILWNNdpVs2WZn/eWlevDrqTgTpo0o+kolzTpFcez3z/C21uxoHMOFx225BGcSO2ix5qPcPbpsl41u5fYDrbpM5vyxSvzAdfpWzKngqH4IJHRtCekgpng5RI5bAuScTSE0Km7wQt+rlZzaT+k3FDr7QH0vQw9gyLpjK+nltWNDAzO/q5qizg/ytCgeB/4zkeZ9M78LxEzl76G5f44KrpkDwY0iwEsHHuUzOy1MKTNSkKqAM+PhN05EJ2iWbwQJD7vtfe4WwtEtvuI0TK0f0s4sz0aD4m8="
script:
# for the time being, these tests will have to be manually run
#- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then npm run test-e2e; fi
- if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then npm run test; fi
- sonar-scanner
notifications:
  email:
    recipients:
      - mikedidomizio@gmail.com
    on_success: never
    on_failure: change